apiVersion: apps/v1
kind: Deployment
metadata:
  name: savannah-app
  labels:
    app: savannah
spec:
  replicas: 3
  selector:
    matchLabels:
      app: savannah
  template:
    metadata:
      labels:
        app: savannah
    spec:
      containers:
      - name: savannah
        image: savannah:test
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database-url
        - name: AFRICA_TALKING_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: africa-talking-key
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
